# Database Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${db_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
logging.level.org.springframework=DEBUG
logging.level.com.example.aggregator=DEBUG
logging.level.org.springframework.security=DEBUG

# Server Port
server.port=8926

# AWS Credentials
#Give your Id and accessKey here
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY}
aws.region=${AWS_REGION}
aws.s3.bucket=${AWS_S3_BUCKET}

